Add function getYears, getMonths, getDays
arduino-libraries/NTPClient pull request #184
Opened 2023-01-12 04:07 UTC by thaianhtaivn

Already tested function with platformIO & ESP8266.

2023-01-12 04:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/NTPClient?pullRequest=184) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/NTPClient?pullRequest=184) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/NTPClient?pullRequest=184) it.</sub>

2023-01-12 04:54 UTC, per1234 commented
Alternative to:

- https://github.com/arduino-libraries/NTPClient/pull/60
- https://github.com/arduino-libraries/NTPClient/pull/161

2023-01-12 06:40 UTC, thaianhtaivn commented
Hello @per1234 ,
Because we usually use it, can we merge these functions to master?
Thank you!

2023-01-12 06:46 UTC, per1234 commented
Hi @thaianhtaivn. Thanks for your pull request. My role in this project is somewhat janitorial in nature. I don't make the decisions about which pull requests are merged or not. I commented to provide some supplemental information that might be of use to the reviewers.

Regards,
Per

2023-01-27 05:38 UTC, lukaszgieraltowski requested changes
Good job. I'd suggest to add `getFormattedDateTime` using new methods. Analogously to `getFormattedTime`.

2023-01-27 05:38 UTC, lukaszgieraltowski commented on NTPClient.cpp
> +    time_t rawtime = this->getEpochTime();
Use two spaces for indentation instead of four.

2023-01-27 05:38 UTC, lukaszgieraltowski commented on NTPClient.h
> +	int getYears() const;
Use two spaces for indentation instead of tab.

2023-01-27 06:24 UTC, lukaszgieraltowski commented
@thaianhtaivn Actually this was already implemented https://github.com/arduino-libraries/NTPClient/pull/94 but not merged :/

2023-03-29 06:09 UTC, closed without merging